### ISSUE TITLE
Follow the instructions...

### ISSUE THREAD

**Issue by MrDutchfighter** [athombv/com.heatmiser#1]
Follow the instructions screen keeps showing with the loading wheel. No set-up is coming to initial set-up the devices of my heatmiser neo.. don't know what I should expect. But I think that I should have the option to enter IP / find my heatmiser devices somehow...

Update: had some time to check the browser inspection log. Seems to be a file missing:

http://xxx.xxx.xxx.xxx/app/com.heatmiser/locales/en.json Failed to load resource: the server responded with a status of 404 (Not Found)

Can't find this file in the repository though...

**Comment by RobinBol** [comment]
Thanks for reporting the issue! It appeared Homey had problems with finding the local ip address, therefore it could not broadcast to find your Heatmiser. This issue should be resolved in version 1.0.2 of the app.

We have only limited testing capabilities here for the Heatmiser, if you encounter any further issues please create an issue on Github again, helps a lot!

**Comment by MrDutchfighter** [comment]
Hi, can you push this to the Homey App Store? Can't download the updated version yet. Or is there another way to test this fix?

**Comment by RobinBol** [comment]
The app update will be available coming Monday or Tuesday, depending on how much time my colleagues have. You can download the zip file of this repo, and install it on your Homey, for instructions see: https://developers.athom.com/library/getting-started/

**Comment by MrDutchfighter** [comment]
Thanks, works! :)

Checked following functionality for now:
- Adding devices
- Reading temperatures
