### ISSUE TITLE
Heatmiser app not working anymore - Device time-out

### ISSUE THREAD

**Issue by robertraaijmakers** [athombv/com.heatmiser#2]
Since Homey version 1.9.1 and also in 1.9.2 the Heatmiser thermostats are not able to be reached through devices (can't read temperature values or set any values in devices, get a red exclamation mark).

**What software are you running**
Homey: 1.9.2
Heatmiser: 1.0.7

**What did I do**
- Go to devices
- Click on the three bars icon (top left of device)
- Wait for a very long time, red exclamation mark icon is visible
(also temperature in insights is not updated anymore)

After this I removed all devices, uninstalled the app, rebooted Homey, installed the app again, added all devices and repeated the above steps. With the same result.

The strange thing is that it finds all the devices and I can add them, but it won't update them and cannot reach a particular device after adding it...

**Comment by RobinBol** [comment]
Fixed in v1.0.8
