### ISSUE TITLE
Incorrect description of "Supported Devices"

### ISSUE THREAD

**Issue by ArchiSpec** [athombv/com.heatmiser#6]
Hi. Just to mention that "Supported Devices" states "Neo Smart" (suggesting talks direct with Homey) whereas discussion on app page suggests that you cannot communicate direct but need a neoHub for all communication. So it would be less confusing if the **_only_** "Supported Device" was **neoHub**. It would also be useful to confirm which version of neoHub it is compatible with - i.e. Gen 1, Gen 2 or both. It would save questions such as this!!

Or will direct communication with stats etc follow in a later release??? It seems pointless having to buy another hub on top of Homey??

Also, will this support the full range of devices via the neoHub, such as neoAir? (Or direct in a future version??)

Thanks for your help.

**Comment by ArchiSpec** [comment]
@RobinBol HI, I see you have assigned as enhancement. Is it just the description of supported devices you plan to enhance, or communication direct with devices (i.e. not relying on NeoHub)?

Thanks - this information would make decision to wait for enhancement or buy Neo Hub possible!

**Comment by ArchiSpec** [comment]
> @RobinBol HI, I see you have assigned as enhancement. Is it just the description of supported devices you plan to enhance, or communication direct with devices (i.e. not relying on NeoHub)?

@RobinBol Hi - just to bump my question above - is it just the description you are "enhancing" or will the enhancement allow Homey to directly communicate with NeoAir stats without the need for the NeoHub???

Thanks in advance.

**Comment by RobinBol** [comment]
Hi, we have no plans to support the devices without the neoHub (not sure if that is even possible). So I'll update the descriptions to make this clearer to the people visiting the app store.
